'use client'
import { useEffect, useState } from 'react'
import { RoleShell } from '@/components/layout/RoleShell'
type Workspace = { stats: { students: number; atRisk: number; improving: number }; students: Array<{ id: string; name: string; stage: string; mastery: number; status: string }> }
export default function TeacherClassesPage() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null)
  useEffect(() => { const sync = () => { let name = ''; try { name = JSON.parse(localStorage.getItem('seekito-profile') ?? '{}').name?.trim() ?? '' } catch {} fetch('/api/teacher/workspace').then((response) => response.json()).then((body) => { const next = body.workspace; if (name && next?.students?.[0]) next.students[0] = { ...next.students[0], name }; setWorkspace(next ?? null) }) }; sync(); window.addEventListener('seekito-profile-updated', sync); return () => window.removeEventListener('seekito-profile-updated', sync) }, [])
  return <RoleShell role="teacher" eyebrow="Teacher console" title="Classes" description="A class-level view of learner progress and support needs."><div className="teacher-demo-page"><section className="teacher-metric-grid">{[['LEARNERS', workspace?.stats.students ?? '—'], ['AT RISK', workspace?.stats.atRisk ?? '—'], ['IMPROVING', workspace?.stats.improving ?? '—'], ['ACTIVE PATH', 'Algebra']].map(([label, value]) => <article className="teacher-metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>Current workspace</small></article>)}</section><section className="teacher-table-card"><div className="teacher-table-header"><div><p className="eyebrow">GRADE 9 · ALGEBRA</p><h2>Class roster</h2></div><span className="teacher-live-status"><i /> Synced from learner state</span></div><div className="teacher-student-table"><div className="teacher-table-heading"><span>STUDENT</span><span>STAGE</span><span>MASTERY</span><span>STATUS</span></div>{workspace?.students.map((student) => <div className="teacher-table-row" style={{ gridTemplateColumns: '1.5fr 1.35fr .65fr 1fr' }} key={student.id}><span className="teacher-student-name"><b>{student.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</b><strong>{student.name}</strong></span><span>{student.stage}</span><strong>{student.mastery}%</strong><span><em className={`teacher-tag ${student.status === 'At risk' || student.status === 'Needs attention' ? 'warn' : 'good'}`}>{student.status}</em></span></div>) ?? <div className="teacher-loading">Loading class roster…</div>}</div></section></div></RoleShell>
}
