'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { AppShell } from '@/components/layout/AppShell'
import { GlowPanel, MasteryRing, SeekitoMascot, SectionHeading, StatusPill, Icon } from '@/components/seekito/SeekitoUI'

type Concept = { id: string; name: string; description: string | null; difficulty: string; subject?: 'ALGEBRA' | 'SCIENCE' }
type State = { concept_id: string; mastery_score: number; confidence_score: number; evidence_count?: number; attempt_count: number; correct_count: number; failure_count: number; recent_streak?: number; updated_at: string }
type Attempt = { id: string; question: string; is_correct: boolean; difficulty: string; submitted_at: string; concept_id: string; used_hint?: boolean }
type Decision = { decision: 'ADVANCE' | 'PRACTICE' | 'REMEDIATE' | 'REVIEW' | 'BLOCKED'; confidence: number; reasons: string[] } | null
type OnboardingProfile = { subject?: 'ALGEBRA' | 'SCIENCE'; conceptIds?: string[]; topicNames?: string[] }

export default function StudentDashboard() {
  const [concepts, setConcepts] = useState<Concept[]>([])
  const [states, setStates] = useState<State[]>([])
  const [attempts, setAttempts] = useState<Attempt[]>([])
  const [decision, setDecision] = useState<Decision>(null)
  const [onboarding, setOnboarding] = useState<OnboardingProfile | null>(null)
  const [error, setError] = useState(false)
  useEffect(() => { try { const stored = sessionStorage.getItem('seekito-onboarding'); if (stored) setOnboarding(JSON.parse(stored) as OnboardingProfile) } catch { setOnboarding(null) } }, [])
  useEffect(() => { Promise.all([fetch('/api/concepts').then((r) => r.json()), fetch('/api/learner-state').then((r) => r.json()), fetch('/api/attempts').then((r) => r.json())]).then(([conceptBody, stateBody, attemptBody]) => { setConcepts(conceptBody.concepts ?? []); if (stateBody.success) setStates(stateBody.learnerState); if (attemptBody.success) setAttempts(attemptBody.attempts) }).catch(() => setError(true)) }, [])
  const visibleConcepts = useMemo(() => { if (!onboarding?.conceptIds?.length) return concepts; const selected = new Set(onboarding.conceptIds); return concepts.filter((concept) => selected.has(concept.id)) }, [concepts, onboarding])
  const visibleStates = useMemo(() => { if (!onboarding?.conceptIds?.length) return states; const selected = new Set(onboarding.conceptIds); return states.filter((state) => selected.has(state.concept_id)) }, [states, onboarding])
  const averageMastery = visibleStates.length ? Math.round(visibleStates.reduce((total, state) => total + Number(state.mastery_score), 0) / visibleStates.length) : null
  const mastered = visibleStates.filter((state) => Number(state.mastery_score) >= 80).length
  const recent = useMemo(() => attempts.filter((attempt) => !onboarding?.conceptIds?.length || onboarding.conceptIds.includes(attempt.concept_id)).slice(0, 4), [attempts, onboarding])
  const focusState = visibleStates.find((state) => Number(state.mastery_score) < 80) ?? visibleStates[0]
  const preferredConcept = visibleConcepts.find((concept) => concept.id === onboarding?.conceptIds?.[0])
  const focusConcept = focusState ? visibleConcepts.find((concept) => concept.id === focusState.concept_id) : preferredConcept ?? visibleConcepts[0]
  const focusMastery = focusState ? Number(focusState.mastery_score) : 0
  const focusConfidence = focusState ? Number(focusState.confidence_score) : 0
  const focusEvidence = focusState?.evidence_count ?? focusState?.attempt_count ?? 0
  useEffect(() => { if (!focusConcept) return; fetch('/api/decision', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetConceptId: focusConcept.id }) }).then((response) => response.json()).then((body) => { if (body.success) setDecision(body.result) }).catch(() => undefined) }, [focusConcept?.id])
  const actionLabel = decision?.decision === 'REMEDIATE' ? 'Remediate' : decision?.decision === 'REVIEW' ? 'Review' : decision?.decision === 'ADVANCE' ? 'Advance' : decision?.decision === 'BLOCKED' ? 'Blocked' : 'Practice'
  const streak = visibleStates.length ? Math.max(...visibleStates.map((state) => Number(state.recent_streak ?? 0))) : 0
  const subjectLabel = focusConcept?.subject === 'SCIENCE' ? 'Science' : 'Mathematics'
  return <AppShell eyebrow={`Seekito / ${subjectLabel}`} title="Good morning, Alex." description="Here's what your learning state looks like today." headerActions={<><div className="header-search"><span>⌕</span><input aria-label="Search concepts and evidence" placeholder="Search concepts, evidence…" /></div><Link className="header-practice-button" href={focusConcept ? `/student/assessment/${focusConcept.id}` : '/student/practice'}><Icon name="spark" />Start Practice</Link></>}><div className="dashboard-stack">
    {error && <div className="inline-error">Unable to load your learning state. Check your account connection and try again.</div>}
    <section className="metric-grid" aria-label="Learning metrics"><Metric label="Current stage" value={focusConcept?.name ?? '—'} detail={focusConcept ? `${subjectLabel} learning path` : 'Complete onboarding to begin'} icon="spark" /><Metric label="Overall mastery" value={averageMastery === null ? '—' : `${averageMastery}%`} detail={visibleStates.length ? 'Across selected concepts' : 'Complete an assessment to begin'} icon="chart" /><Metric label="Concepts mastered" value={visibleConcepts.length ? `${mastered} / ${visibleConcepts.length}` : '—'} detail={visibleConcepts.length ? 'Selected learning path' : 'Choose topics to begin'} icon="check" /><Metric label="Learning streak" value={streak ? `${streak} days` : '—'} detail={streak ? 'Keep the momentum going' : 'No activity yet'} icon="spark" /></section>
    <GlowPanel className="learning-state-panel"><div className="learning-state-copy"><div className="panel-kicker"><span>YOUR NEXT BEST ACTION</span>{decision && <span className={`action-badge action-${decision.decision.toLowerCase()}`}>{actionLabel.toUpperCase()}</span>}</div><h2>{focusConcept ? `${actionLabel} ${focusConcept.name}` : 'Your learning map starts here.'}</h2><p>{decision?.reasons?.[0] ?? (focusState ? 'Your recent evidence points to a focused next step. Continue with a targeted session and keep building confidence.' : 'Complete your first assessment and Seekito will start building your personal learning map.')}</p><div className="learning-state-actions"><Link className="primary-button" href={focusConcept ? `/student/assessment/${focusConcept.id}` : '/student/practice'}><Icon name="spark" />Start Practice</Link><Link className="quiet-link" href={focusConcept ? `/student/decision/${focusConcept.id}` : '/student/concepts'}>Why this recommendation?</Link></div><div className="action-footnote"><span>◉ Decision confidence {decision ? `${Math.round(decision.confidence)}%` : '—'}</span><span>⌁ {focusEvidence} evidence events</span><span>⌘ Prerequisite context included</span></div></div><div className="learning-state-visual"><div className="action-detail-card"><span>{focusConcept?.name ?? 'Concept'} mastery</span><strong>{focusState ? `${Math.round(focusMastery)}%` : '—'}</strong><div className="action-progress"><span style={{ width: `${Math.min(100, focusMastery)}%` }} /></div><dl><div><dt>Confidence</dt><dd>{focusState ? `${Math.round(focusConfidence)}%` : '—'}</dd></div><div><dt>Evidence</dt><dd>{focusState ? focusEvidence : '—'}</dd></div><div><dt>Last practiced</dt><dd>{focusState?.updated_at ? new Date(focusState.updated_at).toLocaleDateString() : '—'}</dd></div></dl></div></div></GlowPanel>
    <div className="dashboard-columns"><section className="panel-card"><SectionHeading title="Concept mastery" action={<Link href="/student/concepts">View concept map</Link>} />{visibleStates.length ? <div className="mastery-list">{visibleStates.slice(0, 6).map((state) => { const concept = visibleConcepts.find((item) => item.id === state.concept_id); const mastery = Number(state.mastery_score); const tone = mastery >= 80 ? 'positive' : mastery < 45 ? 'warning' : 'blue'; const label = mastery >= 80 ? 'Mastered' : mastery < 45 ? 'Needs Attention' : 'Learning'; return <Link href={`/student/decision/${state.concept_id}`} className="mastery-row" key={state.concept_id}><span className="mastery-row-head"><span className="mastery-name">{concept?.name ?? 'Concept'}</span><span className="mastery-row-meta"><StatusPill tone={tone}>{label}</StatusPill><strong>{Math.round(mastery)}%</strong></span></span><span className="progress-track"><span className={`progress-${tone}`} style={{ width: `${Math.min(100, mastery)}%` }} /></span></Link> })}</div> : <EmptyState title="No learning profile yet" copy="Complete your first assessment to start building your learning profile." href="/student/practice" action="Start practice" />}</section><section className="panel-card evidence-panel"><SectionHeading title="Latest evidence" action={<Link href="/student/history">View history</Link>} />{recent.length ? <div className="evidence-list">{recent.slice(0, 3).map((attempt) => <Link href="/student/history" className="evidence-card" key={attempt.id}><span className={`evidence-icon ${attempt.is_correct ? 'evidence-success' : 'evidence-error'}`}>{attempt.is_correct ? '✓' : '×'}</span><span className="evidence-copy"><strong>{attempt.question}</strong><small>{attempt.difficulty} · {new Date(attempt.submitted_at).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}{attempt.used_hint ? ' · Hint used' : ''}</small></span><StatusPill tone={attempt.is_correct ? 'positive' : 'danger'}>{attempt.is_correct ? 'Correct' : 'Incorrect'}</StatusPill></Link>)}</div> : <EmptyState title="No evidence yet" copy="Complete your first assessment and Seekito will start building your learning map." href="/student/practice" action="Start practice" />}<div className="evidence-explanation"><strong>Why this focus?</strong><span>Seekito uses your attempts, hints, and prerequisite context to explain the next step.</span></div></section></div>
    <section className="dashboard-callout"><div><p className="eyebrow">Understand the why</p><h2>Every decision has a trace.</h2><p>Explore a concept to see the prerequisite evidence and learner state behind your next learning decision.</p></div><Link className="secondary-button" href="/student/concepts">Open concept map</Link></section>
  </div></AppShell>
}

function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: 'spark' | 'chart' | 'check' }) { return <article className="metric-card"><div className="metric-head"><span>{label}</span><span className="metric-icon"><Icon name={icon} /></span></div><strong>{value}</strong><small>{detail}</small></article> }
function EmptyState({ title, copy, href, action }: { title: string; copy: string; href: '/student/practice' | '/student/concepts'; action: string }) { return <div className="empty-state"><span className="empty-glyph">○</span><h3>{title}</h3><p>{copy}</p><Link className="text-link" href={href}>{action} →</Link></div> }
