'use client'

import { useEffect, useState } from 'react'
import { RoleShell } from '@/components/layout/RoleShell'

type Analytics = { averageMastery: number; concepts: Array<{ name: string; mastery: number }>; difficulty: Array<{ level: string; accuracy: number }>; activity: number[] }

export default function TeacherAnalyticsPage() {
  const [data, setData] = useState<Analytics | null>(null)
  useEffect(() => { fetch('/api/teacher/analytics').then((r) => r.json()).then((body) => setData(body.analytics ?? null)) }, [])
  return <RoleShell role="teacher" eyebrow="Teacher console" title="Analytics" description="Class-level trends computed from captured learner evidence."><div className="teacher-demo-page"><div className="teacher-demo-actions"><span className="teacher-live-status"><i /> {data ? 'Analytics synced with learner state' : 'Loading analytics…'}</span><span className="eyebrow">LAST 14 DAYS</span></div><div className="analytics-grid"><AnalyticsCard title="CLASS MASTERY"><div className="analytics-highlight"><strong>{data ? `${data.averageMastery}% average mastery` : 'Loading…'}</strong><span>Evidence-backed</span></div><div className="analytics-line-chart"><svg viewBox="0 0 700 150" role="img" aria-label="Class mastery trend"><path d="M0 130 C110 121 145 110 220 104 S330 88 395 78 S500 45 565 42 S640 24 700 10" fill="none" stroke="var(--primary)" strokeWidth="4" strokeLinecap="round" /></svg></div></AnalyticsCard><AnalyticsCard title="ACCURACY BY DIFFICULTY"><h2>Where learners are getting stuck</h2>{(data?.difficulty ?? []).map(({ level, accuracy }) => <div className="difficulty-row" key={level}><span>{level}</span><div className="difficulty-track"><i className={level === 'EASY' ? 'easy' : level === 'MEDIUM' ? 'medium' : 'hard'} style={{ width: `${accuracy}%` }} /></div><strong>{accuracy}%</strong></div>)}<div className="analytics-note">Hard-item accuracy is the main drag on prerequisite readiness.</div></AnalyticsCard><AnalyticsCard title="CONCEPT COMPARISON"><h2>Mastery by concept</h2>{(data?.concepts ?? []).map(({ name, mastery }) => <div className="analytics-bar-row" key={name}><span>{name}</span><div className="analytics-bar-track"><i className={mastery < 50 ? 'hard' : mastery < 70 ? 'medium' : 'easy'} style={{ width: `${mastery}%` }} /></div><strong>{mastery}%</strong></div>)}</AnalyticsCard><AnalyticsCard title="PRACTICE ACTIVITY"><h2>Attempts captured</h2><div className="analytics-activity">{(data?.activity ?? []).map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div><div className="analytics-axis"><span>Earlier</span><span>Recent</span><span>Today</span></div></AnalyticsCard></div></div></RoleShell>
}

function AnalyticsCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="analytics-card"><p className="eyebrow">{title}</p>{children}</section> }
