import type { DecisionResult } from '@/lib/decision-engine'

export const DEMO_STUDENT_ID = '00000000-0000-0000-0000-000000000001'
const ids = { arithmetic: '10000000-0000-4000-8000-000000000001', fractions: '10000000-0000-4000-8000-000000000002', operations: '10000000-0000-4000-8000-000000000003', linear: '10000000-0000-4000-8000-000000000004', quadratic: '10000000-0000-4000-8000-000000000005', scientificBasics: '10000000-0000-4000-8000-000000000006', forceMotion: '10000000-0000-4000-8000-000000000007', newtonsLaws: '10000000-0000-4000-8000-000000000008', workEnergy: '10000000-0000-4000-8000-000000000009', momentum: '10000000-0000-4000-8000-000000000010' }
export function canonicalDemoConceptId(id: string) { const match = id.match(/([1-5])$/); return match ? Object.values(ids)[Number(match[1]) - 1] : id }
export const demoConcepts = [
  { id: ids.arithmetic, name: 'Basic Arithmetic', slug: 'basic-arithmetic', description: 'Core operations and number sense.', subject: 'ALGEBRA', difficulty: 'BEGINNER', estimated_minutes: 15, is_active: true },
  { id: ids.fractions, name: 'Fractions', slug: 'fractions', description: 'Equivalent fractions and operations.', subject: 'ALGEBRA', difficulty: 'BEGINNER', estimated_minutes: 20, is_active: true },
  { id: ids.operations, name: 'Algebraic Operations', slug: 'algebraic-operations', description: 'Simplify and manipulate expressions.', subject: 'ALGEBRA', difficulty: 'INTERMEDIATE', estimated_minutes: 25, is_active: true },
  { id: ids.linear, name: 'Linear Equations', slug: 'linear-equations', description: 'Solve equations one step at a time.', subject: 'ALGEBRA', difficulty: 'INTERMEDIATE', estimated_minutes: 25, is_active: true },
  { id: ids.quadratic, name: 'Quadratic Equations', slug: 'quadratic-equations', description: 'Build toward quadratic reasoning.', subject: 'ALGEBRA', difficulty: 'ADVANCED', estimated_minutes: 30, is_active: true },
  { id: ids.scientificBasics, name: 'Scientific Basics', slug: 'scientific-basics', description: 'Ask questions, test ideas, and interpret evidence.', subject: 'SCIENCE', difficulty: 'BEGINNER', estimated_minutes: 20, is_active: true },
  { id: ids.forceMotion, name: 'Force & Motion', slug: 'force-motion', description: 'Describe how forces change the motion of objects.', subject: 'SCIENCE', difficulty: 'BEGINNER', estimated_minutes: 20, is_active: true },
  { id: ids.newtonsLaws, name: "Newton's Laws", slug: 'newtons-laws', description: 'Connect force, mass, acceleration, and action-reaction pairs.', subject: 'SCIENCE', difficulty: 'INTERMEDIATE', estimated_minutes: 25, is_active: true },
  { id: ids.workEnergy, name: 'Work & Energy', slug: 'work-energy', description: 'Explore work, energy transfer, and conservation.', subject: 'SCIENCE', difficulty: 'INTERMEDIATE', estimated_minutes: 25, is_active: true },
  { id: ids.momentum, name: 'Momentum', slug: 'momentum', description: 'Reason about mass, velocity, and collisions.', subject: 'SCIENCE', difficulty: 'ADVANCED', estimated_minutes: 30, is_active: true },
]
export const demoPrerequisites = [...[ids.fractions, ids.operations, ids.linear, ids.quadratic].map((conceptId, index) => ({ id: `20000000-0000-4000-8000-00000000000${index + 1}`, concept_id: conceptId, prerequisite_concept_id: [ids.arithmetic, ids.fractions, ids.operations, ids.linear][index], required_mastery: 0.6, priority: 1 })), ...[ids.forceMotion, ids.newtonsLaws, ids.workEnergy, ids.momentum].map((conceptId, index) => ({ id: `20000000-0000-4000-8000-0000000000${index + 6}`, concept_id: conceptId, prerequisite_concept_id: [ids.scientificBasics, ids.forceMotion, ids.newtonsLaws, ids.workEnergy][index], required_mastery: 0.6, priority: 1 }))]
type DemoQuestion = { id: string; concept_id: string; concept: typeof demoConcepts[number]; question: string; options: string[]; correctAnswer: string; explanation: string; difficulty: string; questionType: 'MCQ'; hintAvailable: boolean; hint: string }
export const demoQuestions: DemoQuestion[] = [
  { id: '30000000-0000-4000-8000-000000000001', concept_id: ids.operations, concept: demoConcepts[2], question: 'Simplify: 3x + 2x', options: ['5x', '6x', 'x⁵'], correctAnswer: '5x', explanation: 'Combine like terms by adding their coefficients.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Look for terms with the same variable.' },
  { id: '30000000-0000-4000-8000-000000000002', concept_id: ids.operations, concept: demoConcepts[2], question: 'Simplify: 2(a + 3)', options: ['2a + 3', '2a + 6', 'a + 6'], correctAnswer: '2a + 6', explanation: 'Distribute 2 to both terms inside the parentheses.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Multiply the outside number by each inside term.' },
  { id: '30000000-0000-4000-8000-000000000003', concept_id: ids.operations, concept: demoConcepts[2], question: 'What is the coefficient of y in 7y + 4?', options: ['4', '7', 'y'], correctAnswer: '7', explanation: 'The coefficient is the number multiplying the variable.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Find the number directly next to y.' },
  { id: '30000000-0000-4000-8000-000000000004', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 1/2 + 1/4?', options: ['2/6', '3/4', '1/6'], correctAnswer: '3/4', explanation: 'Convert both fractions to fourths, then add.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Use a common denominator of 4.' },
  { id: '30000000-0000-4000-8000-000000000005', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: x + 4 = 9', options: ['3', '5', '13'], correctAnswer: '5', explanation: 'Subtract 4 from both sides.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Undo the +4 operation.' },
  { id: '30000000-0000-4000-8000-000000000006', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 7 × 8?', options: ['48', '56', '64'], correctAnswer: '56', explanation: 'Seven groups of eight equal fifty-six.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think of 7 groups of 8.' },
  { id: '30000000-0000-4000-8000-000000000007', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 45 ÷ 5?', options: ['8', '9', '10'], correctAnswer: '9', explanation: 'Five groups of nine make forty-five.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think about the multiplication fact 5 × ? = 45.' },
  { id: '30000000-0000-4000-8000-000000000008', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 18 + 27?', options: ['35', '45', '55'], correctAnswer: '45', explanation: 'Add the tens and ones: 18 + 27 = 45.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Add 20, then add 7.' },
  { id: '30000000-0000-4000-8000-000000000009', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'Which number is prime?', options: ['21', '29', '35'], correctAnswer: '29', explanation: '29 has no factors other than 1 and itself.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Check whether any smaller prime divides it.' },
  { id: '30000000-0000-4000-8000-000000000010', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 6²?', options: ['12', '30', '36'], correctAnswer: '36', explanation: '6² means 6 × 6, which equals 36.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Multiply 6 by itself.' },
]

demoQuestions.push(
  { id: '30000000-0000-4000-8000-000000000011', concept_id: ids.fractions, concept: demoConcepts[1], question: 'Which fraction is equivalent to 2/3?', options: ['4/6', '3/5', '5/8'], correctAnswer: '4/6', explanation: 'Multiply both numerator and denominator by 2.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Scale both parts by the same number.' },
  { id: '30000000-0000-4000-8000-000000000012', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 3/4 − 1/4?', options: ['1/2', '2/4', '3/8'], correctAnswer: '1/2', explanation: 'Subtract the numerators over the common denominator, then simplify.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'The denominators already match.' },
  { id: '30000000-0000-4000-8000-000000000013', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 2/5 × 5?', options: ['2', '10/5', '1/5'], correctAnswer: '2', explanation: 'The 5 in the numerator and denominator cancel.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Rewrite 5 as 5/1.' },
  { id: '30000000-0000-4000-8000-000000000014', concept_id: ids.fractions, concept: demoConcepts[1], question: 'Which is larger?', options: ['3/8', '1/2', 'They are equal'], correctAnswer: '1/2', explanation: 'One half is four eighths, which is greater than three eighths.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Convert both to eighths.' },
  { id: '30000000-0000-4000-8000-000000000015', concept_id: ids.operations, concept: demoConcepts[2], question: 'Simplify: 4x − x', options: ['3x', '4', 'x³'], correctAnswer: '3x', explanation: 'Subtract the coefficients of like terms.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Treat x as 1x.' },
  { id: '30000000-0000-4000-8000-000000000016', concept_id: ids.operations, concept: demoConcepts[2], question: 'Evaluate 2x + 1 when x = 3.', options: ['5', '7', '9'], correctAnswer: '7', explanation: 'Substitute 3 for x: 2(3) + 1 = 7.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Replace x with 3.' },
  { id: '30000000-0000-4000-8000-000000000017', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: 2x = 14', options: ['6', '7', '12'], correctAnswer: '7', explanation: 'Divide both sides by 2.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Undo multiplication by 2.' },
  { id: '30000000-0000-4000-8000-000000000018', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: 3x − 2 = 10', options: ['2', '4', '6'], correctAnswer: '4', explanation: 'Add 2, then divide by 3.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Undo operations in reverse order.' },
  { id: '30000000-0000-4000-8000-000000000019', concept_id: ids.linear, concept: demoConcepts[3], question: 'Which value solves x/4 = 3?', options: ['7', '12', '16'], correctAnswer: '12', explanation: 'Multiply both sides by 4.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Undo division by 4.' },
  { id: '30000000-0000-4000-8000-000000000020', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: 5 + x = 2x', options: ['3', '5', '10'], correctAnswer: '5', explanation: 'Subtract x from both sides, leaving 5 = x.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Collect x terms on one side.' },
  { id: '30000000-0000-4000-8000-000000000021', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'Which is a factorisation of x² + 5x + 6?', options: ['(x + 2)(x + 3)', '(x + 1)(x + 6)', '(x − 2)(x − 3)'], correctAnswer: '(x + 2)(x + 3)', explanation: 'Two numbers multiply to 6 and add to 5.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Look for factors of 6 that add to 5.' },
  { id: '30000000-0000-4000-8000-000000000022', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'What is the highest power in 3x² + x − 4?', options: ['1', '2', '4'], correctAnswer: '2', explanation: 'The degree is the highest exponent of the variable.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Find the largest exponent.' },
  { id: '30000000-0000-4000-8000-000000000023', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'Solve x² = 25.', options: ['x = 5 only', 'x = ±5', 'x = 25'], correctAnswer: 'x = ±5', explanation: 'Both 5² and (−5)² equal 25.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'A square has two possible roots.' },
  { id: '30000000-0000-4000-8000-000000000024', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'What is the discriminant of x² − 4x + 3?', options: ['4', '8', '16'], correctAnswer: '4', explanation: 'The discriminant is b² − 4ac = 16 − 12 = 4.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Use b² − 4ac.' },
  { id: '30000000-0000-4000-8000-000000000025', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'Which graph represents a positive quadratic coefficient?', options: ['A parabola opening up', 'A parabola opening down', 'A straight line'], correctAnswer: 'A parabola opening up', explanation: 'A positive leading coefficient makes the parabola open upward.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think about the direction of the arms.' },
  { id: '30000000-0000-4000-8000-000000000026', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'What is a testable explanation called?', options: ['A hypothesis', 'A conclusion', 'A measurement'], correctAnswer: 'A hypothesis', explanation: 'A hypothesis is a proposed explanation that can be tested.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'It is an idea you can investigate.' },
  { id: '30000000-0000-4000-8000-000000000027', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'What should you do after collecting results?', options: ['Ignore them', 'Analyse the evidence', 'Change the question randomly'], correctAnswer: 'Analyse the evidence', explanation: 'Scientists analyse results to decide what the evidence shows.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Look for patterns in the data.' },
  { id: '30000000-0000-4000-8000-000000000028', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'Which variable is deliberately changed in an investigation?', options: ['Independent variable', 'Control variable', 'Dependent variable'], correctAnswer: 'Independent variable', explanation: 'The independent variable is the factor the investigator changes.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'It is the input you choose to change.' },
  { id: '30000000-0000-4000-8000-000000000029', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'Why repeat an experiment?', options: ['To make the result less reliable', 'To check consistency', 'To avoid recording data'], correctAnswer: 'To check consistency', explanation: 'Repeating an experiment helps identify unusual results and check reliability.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Reliable results can be reproduced.' },
  { id: '30000000-0000-4000-8000-000000000030', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'Which is the best scientific conclusion?', options: ['It is definitely true forever', 'The evidence supports the hypothesis', 'The data does not matter'], correctAnswer: 'The evidence supports the hypothesis', explanation: 'Conclusions should match the evidence without claiming more than the data shows.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Use cautious language based on evidence.' },
  { id: '30000000-0000-4000-8000-000000000031', concept_id: ids.forceMotion, concept: demoConcepts[6], question: 'What is a force?', options: ['A push or pull', 'A type of energy only', 'An object at rest'], correctAnswer: 'A push or pull', explanation: 'A force is a push or pull that can change an object’s motion.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think about what can start or stop motion.' },
  { id: '30000000-0000-4000-8000-000000000032', concept_id: ids.forceMotion, concept: demoConcepts[6], question: 'What does speed describe?', options: ['Distance travelled per unit of time', 'Mass multiplied by force', 'Energy stored in an object'], correctAnswer: 'Distance travelled per unit of time', explanation: 'Speed tells us how much distance an object covers in a given time.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Use the relationship distance divided by time.' },
  { id: '30000000-0000-4000-8000-000000000033', concept_id: ids.forceMotion, concept: demoConcepts[6], question: 'What happens when an unbalanced force acts on an object?', options: ['Its motion changes', 'Its mass disappears', 'Time stops'], correctAnswer: 'Its motion changes', explanation: 'An unbalanced force causes acceleration, changing speed or direction.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Think about acceleration.' },
  { id: '30000000-0000-4000-8000-000000000034', concept_id: ids.forceMotion, concept: demoConcepts[6], question: 'Which change is acceleration?', options: ['A change in velocity', 'A change in colour', 'A change in mass only'], correctAnswer: 'A change in velocity', explanation: 'Acceleration is the rate at which velocity changes.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Velocity includes speed and direction.' },
  { id: '30000000-0000-4000-8000-000000000035', concept_id: ids.forceMotion, concept: demoConcepts[6], question: 'Which graph best represents constant speed?', options: ['A straight distance-time line', 'A random zigzag line', 'A flat force-time line only'], correctAnswer: 'A straight distance-time line', explanation: 'A straight distance-time line shows equal distances travelled in equal times.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Look for a constant slope.' },
)

demoQuestions.push(
  ...['What is the relationship between force, mass, and acceleration?', 'Which law describes inertia?', 'Which force pulls objects toward Earth?', 'What unit measures force?', 'What happens when friction increases?'].map((question, index) => ({ id: `30000000-0000-4000-8000-${String(index + 36).padStart(12, '0')}`, concept_id: ids.newtonsLaws, concept: demoConcepts[7], question, options: index === 0 ? ['F = ma', 'F = m/a', 'F = a/m'] : ['Newton’s First Law', 'Newton’s Second Law', 'Newton’s Third Law'], correctAnswer: index === 0 ? 'F = ma' : index === 1 ? 'Newton’s First Law' : index === 2 ? 'Newton’s Second Law' : index === 3 ? 'Newton’s Second Law' : 'Newton’s First Law', explanation: 'Newton’s laws connect forces and motion through testable relationships.', difficulty: index > 2 ? 'MEDIUM' : 'EASY', questionType: 'MCQ' as const, hintAvailable: true, hint: 'Recall the force and motion relationship.' })),
  ...['What is work in physics?', 'Which form of energy is stored due to height?', 'What happens to energy in a closed system?', 'Which object has more kinetic energy?', 'What is power a measure of?'].map((question, index) => ({ id: `30000000-0000-4000-8000-${String(index + 41).padStart(12, '0')}`, concept_id: ids.workEnergy, concept: demoConcepts[8], question, options: ['Energy transferred by a force', 'Mass only', 'Time only'], correctAnswer: index === 1 ? 'Energy transferred by a force' : 'Energy transferred by a force', explanation: 'Work and energy describe how forces transfer and transform energy.', difficulty: index > 2 ? 'MEDIUM' : 'EASY', questionType: 'MCQ' as const, hintAvailable: true, hint: 'Think about energy transfer.' })),
  ...['What is momentum?', 'How is momentum calculated?', 'What happens to momentum in an isolated collision?', 'Which object has greater momentum?', 'Why do airbags reduce injury?'].map((question, index) => ({ id: `30000000-0000-4000-8000-${String(index + 46).padStart(12, '0')}`, concept_id: ids.momentum, concept: demoConcepts[9], question, options: ['Mass × velocity', 'Mass + velocity', 'Force ÷ time'], correctAnswer: 'Mass × velocity', explanation: 'Momentum depends on both mass and velocity and is conserved in an isolated system.', difficulty: index > 2 ? 'HARD' : 'MEDIUM', questionType: 'MCQ' as const, hintAvailable: true, hint: 'Use p = mv.' })),
)
demoQuestions.push(
  { id: '30000000-0000-4000-8000-000000000051', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 5/6 + 1/6?', options: ['1', '5/12', '6/12'], correctAnswer: '1', explanation: 'Add the numerators because the denominators match.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Keep the denominator and add the top numbers.' },
  { id: '30000000-0000-4000-8000-000000000052', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 2/3 of 9?', options: ['3', '6', '9'], correctAnswer: '6', explanation: 'Divide 9 into thirds, then take two of those parts.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Find one third of 9 first.' },
  { id: '30000000-0000-4000-8000-000000000053', concept_id: ids.fractions, concept: demoConcepts[1], question: 'Which fraction is already in simplest form?', options: ['6/8', '9/12', '5/7'], correctAnswer: '5/7', explanation: 'Five and seven have no common factor greater than one.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Look for a common factor in the numerator and denominator.' },
  { id: '30000000-0000-4000-8000-000000000054', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 3/5 ÷ 1/5?', options: ['1', '3', '15'], correctAnswer: '3', explanation: 'There are three one-fifths in three-fifths.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Ask how many one-fifths fit into three-fifths.' },
  { id: '30000000-0000-4000-8000-000000000055', concept_id: ids.fractions, concept: demoConcepts[1], question: 'Which decimal equals 3/4?', options: ['0.34', '0.75', '0.25'], correctAnswer: '0.75', explanation: 'Three divided by four equals seventy-five hundredths.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Convert the fraction by dividing 3 by 4.' },
)
demoQuestions.push(
  { id: '30000000-0000-4000-8000-000000000056', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'Which tool measures temperature?', options: ['Thermometer', 'Balance', 'Ruler'], correctAnswer: 'Thermometer', explanation: 'A thermometer measures how hot or cold something is.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'It is used to measure heat.' },
  { id: '30000000-0000-4000-8000-000000000057', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'What is a fair test?', options: ['Changing one variable at a time', 'Changing every variable', 'Skipping measurements'], correctAnswer: 'Changing one variable at a time', explanation: 'A fair test isolates the effect of the independent variable.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Keep other conditions controlled.' },
  { id: '30000000-0000-4000-8000-000000000058', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'What does a control variable do?', options: ['It stays the same', 'It is always changed', 'It is never measured'], correctAnswer: 'It stays the same', explanation: 'Control variables are kept constant so the comparison is meaningful.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Think about what you keep constant.' },
  { id: '30000000-0000-4000-8000-000000000059', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'Which unit commonly measures mass?', options: ['Grams', 'Litres', 'Seconds'], correctAnswer: 'Grams', explanation: 'Mass is commonly measured in grams or kilograms.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'It measures how much matter is present.' },
  { id: '30000000-0000-4000-8000-000000000060', concept_id: ids.scientificBasics, concept: demoConcepts[5], question: 'Why record measurements carefully?', options: ['To support reliable conclusions', 'To make results random', 'To avoid evidence'], correctAnswer: 'To support reliable conclusions', explanation: 'Accurate records let you analyse evidence and repeat the investigation.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Good evidence supports a conclusion.' },
)
demoQuestions.push(
  { id: '30000000-0000-4000-8000-000000000061', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 125 + 75?', options: ['180', '200', '225'], correctAnswer: '200', explanation: 'Add the hundreds, tens, and ones to get 200.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Add 100, then 25, then 75.' },
  { id: '30000000-0000-4000-8000-000000000062', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 9 × 6?', options: ['45', '54', '63'], correctAnswer: '54', explanation: 'Nine groups of six equal fifty-four.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Use the six times table.' },
  { id: '30000000-0000-4000-8000-000000000063', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 84 ÷ 7?', options: ['10', '12', '14'], correctAnswer: '12', explanation: 'Seven groups of twelve make eighty-four.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think 7 × ? = 84.' },
  { id: '30000000-0000-4000-8000-000000000064', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'Which number is even?', options: ['17', '23', '42'], correctAnswer: '42', explanation: 'Even numbers divide exactly by two.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Check divisibility by two.' },
  { id: '30000000-0000-4000-8000-000000000065', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 15% of 100?', options: ['5', '15', '25'], correctAnswer: '15', explanation: 'One percent of 100 is one, so fifteen percent is 15.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Percent means out of 100.' },
)
type DemoAttempt = { id: string; questionId: string; conceptId: string; question: string; isCorrect: boolean; submittedAt: string; usedHint: boolean; hintCount: number; responseTimeMs: number | null; retryNumber: number }
let attempts: DemoAttempt[] = []
let demoOverrideLog: Array<{ id: string; student: string; concept: string; conceptId: string; action: string; reason: string; createdAt: string }> = []
type DemoPracticeSession = { id: string; recommendationId: string | null; conceptId: string; actionType: 'practice' | 'remediation' | 'review' | 'advance' | 'teach_prerequisite'; questionIds: string[]; completedQuestionIds: string[]; currentQuestion: number; score: number; status: 'ACTIVE' | 'COMPLETED'; startedAt: string; completedAt?: string }
let practiceSessions: DemoPracticeSession[] = []
let mastery: Record<string, number> = { [ids.arithmetic]: 84, [ids.fractions]: 55, [ids.operations]: 28 }
function seedDemoAttempts(): DemoAttempt[] { const now = Date.now(); const seeds = [{ questionId: '30000000-0000-4000-8000-000000000004', correct: true, hintCount: 0, time: 18400, retry: 0 }, { questionId: '30000000-0000-4000-8000-000000000011', correct: false, hintCount: 1, time: 41200, retry: 0 }, { questionId: '30000000-0000-4000-8000-000000000011', correct: true, hintCount: 1, time: 28700, retry: 1 }, { questionId: '30000000-0000-4000-8000-000000000012', correct: true, hintCount: 0, time: 22100, retry: 0 }, { questionId: '30000000-0000-4000-8000-000000000001', correct: false, hintCount: 2, time: 53600, retry: 0 }]; return seeds.map((seed, index) => { const question = demoQuestions.find((item) => item.id === seed.questionId)!; return { id: `seed-${index + 1}`, questionId: question.id, conceptId: question.concept_id, question: question.question, isCorrect: seed.correct, submittedAt: new Date(now - (seeds.length - index) * 86_400_000).toISOString(), usedHint: seed.hintCount > 0, hintCount: seed.hintCount, responseTimeMs: seed.time, retryNumber: seed.retry } }) }
attempts = seedDemoAttempts()
export function isDemoMode() { return process.env.NODE_ENV !== 'production' && process.env.SEEKITO_DEMO_MODE === 'true' }
export function resetDemo(options: { seed?: boolean } = {}) { attempts = options.seed === false ? [] : seedDemoAttempts(); practiceSessions = []; demoOverrideLog = []; mastery = options.seed === false ? {} : { [ids.arithmetic]: 84, [ids.fractions]: 55, [ids.operations]: 28 } }
export function demoStates() { return Object.entries(mastery).map(([concept_id, mastery_score]) => ({ concept_id, mastery_score, confidence_score: Math.min(90, mastery_score + 10), attempt_count: attempts.filter((item) => item.conceptId === concept_id).length, correct_count: attempts.filter((item) => item.conceptId === concept_id && item.isCorrect).length, failure_count: attempts.filter((item) => item.conceptId === concept_id && !item.isCorrect).length, evidence_count: attempts.filter((item) => item.conceptId === concept_id).length, updated_at: new Date().toISOString() })) }
export function demoAttempts() { return attempts.slice().reverse() }
export function demoEvidence() { return attempts.slice().reverse().map((item) => ({ id: `e-${item.id}`, attempt_id: item.id, concept_id: item.conceptId, evidence_type: item.isCorrect ? 'CORRECT_INDEPENDENT' : 'INCORRECT', created_at: item.submittedAt })) }
export function demoSubmit(questionId: string, answer: string, usedHint: boolean, hintCount = usedHint ? 1 : 0, responseTimeMs: number | null = null) { const question = demoQuestions.find((item) => item.id === questionId); if (!question) return null; const isCorrect = answer.trim().toLowerCase() === question.correctAnswer.toLowerCase(); const id = `a-${Date.now()}-${attempts.length}`; const now = new Date(); const prior = attempts.slice().reverse().find((item) => item.conceptId === question.concept_id && item.questionId === questionId); const retryNumber = prior ? prior.retryNumber + 1 : 0; const rapidRetry = prior ? now.getTime() - new Date(prior.submittedAt).getTime() < 30_000 : false; attempts.push({ id, questionId, conceptId: question.concept_id, question: question.question, isCorrect, submittedAt: now.toISOString(), usedHint, hintCount, responseTimeMs, retryNumber }); const currentMastery = mastery[question.concept_id] ?? 0; const gain = isCorrect ? rapidRetry ? usedHint ? 2 : 5 : usedHint ? 10 : 20 : -15; mastery[question.concept_id] = Math.max(0, Math.min(100, currentMastery + gain)); return { id, isCorrect, question } }
export function demoOverrides() { return demoOverrideLog.slice().reverse() }
export function demoAddOverride(input: { action: string; reason: string; concept?: string; conceptId?: string }) { const item = { id: `override-${Date.now()}`, student: 'Alex Carter', concept: input.concept ?? 'Fractions', conceptId: input.conceptId ?? ids.fractions, action: input.action, reason: input.reason, createdAt: new Date().toISOString() }; demoOverrideLog.push(item); return item }
export function demoStartPractice(input: { conceptId: string; actionType: DemoPracticeSession['actionType']; recommendationId?: string | null; questionCount?: number }) { const difficultyOrder = input.actionType === 'remediation' || input.actionType === 'teach_prerequisite' ? ['EASY', 'MEDIUM', 'HARD'] : input.actionType === 'advance' ? ['MEDIUM', 'HARD', 'EASY'] : input.actionType === 'review' ? ['MEDIUM', 'EASY', 'HARD'] : ['MEDIUM', 'EASY', 'HARD']; const requestedCount = [10, 15, 20].includes(input.questionCount ?? 10) ? input.questionCount ?? 10 : 10; const pool = demoQuestions.filter((item) => item.concept_id === input.conceptId).sort((a, b) => difficultyOrder.indexOf(a.difficulty) - difficultyOrder.indexOf(b.difficulty) || a.id.localeCompare(b.id)); const questions = Array.from({ length: Math.min(requestedCount, Math.max(pool.length, 1) * 4) }, (_, index) => { const item = pool[index % pool.length]; return index < pool.length ? item : { ...item, id: `${item.id}::variant-${index}` } }); if (!questions.length || !pool.length) return null; const session: DemoPracticeSession = { id: `session-${Date.now()}`, recommendationId: input.recommendationId ?? null, conceptId: input.conceptId, actionType: input.actionType, questionIds: questions.map((item) => item.id), completedQuestionIds: [], currentQuestion: 0, score: 0, status: 'ACTIVE', startedAt: new Date().toISOString() }; practiceSessions.push(session); return { session, questions } }
export function demoPracticeSession(id: string) { return practiceSessions.find((session) => session.id === id) ?? null }
export function demoSubmitPractice(sessionId: string, questionId: string, answer: string, usedHint: boolean, hintCount = usedHint ? 1 : 0, responseTimeMs: number | null = null) { const session = demoPracticeSession(sessionId); if (!session) return { error: 'Practice session not found' as const }; if (session.status !== 'ACTIVE') return { error: 'Practice session is already complete' as const }; if (!session.questionIds.includes(questionId)) return { error: 'Question is not part of this practice session' as const }; if (session.completedQuestionIds.includes(questionId)) return { error: 'This question has already been submitted' as const }; if (questionId !== session.questionIds[session.currentQuestion]) return { error: 'Submit the current question before continuing' as const }; const baseQuestionId = questionId.split('::')[0]; const submission = demoSubmit(baseQuestionId, answer, usedHint, hintCount, responseTimeMs); if (!submission) return { error: 'Question not found' as const }; session.completedQuestionIds.push(questionId); session.currentQuestion += 1; if (submission.isCorrect) session.score += 1; if (session.currentQuestion >= session.questionIds.length) { session.status = 'COMPLETED'; session.completedAt = new Date().toISOString() } return { session, submission } }
export function demoDecision(conceptId: string): DecisionResult { const state = mastery[conceptId] ?? 0; const blocking = demoPrerequisites.filter((edge) => edge.concept_id === conceptId && (mastery[edge.prerequisite_concept_id] ?? 0) < edge.required_mastery * 100).map((edge) => ({ conceptId: edge.prerequisite_concept_id, conceptName: demoConcepts.find((item) => item.id === edge.prerequisite_concept_id)?.name ?? 'Prerequisite', mastery: mastery[edge.prerequisite_concept_id] ?? 0, threshold: edge.required_mastery * 100 })); const latestOverride = demoOverrideLog.slice().reverse().find((item) => item.conceptId === conceptId); const engineDecision = blocking.length ? 'BLOCKED' : state < 40 ? 'REMEDIATE' : state < 70 ? 'PRACTICE' : 'ADVANCE'; const overrideDecision = latestOverride?.action === 'review' ? 'REVIEW' : latestOverride?.action === 'advance' ? 'ADVANCE' : latestOverride?.action === 'remediation' || latestOverride?.action === 'teacher_intervention' ? 'REMEDIATE' : latestOverride?.action === 'teach_prerequisite' ? 'BLOCKED' : latestOverride?.action === 'practice' ? 'PRACTICE' : null; const decision = overrideDecision ?? engineDecision; const reasons = blocking.length && !overrideDecision ? [`Strengthen ${blocking[0].conceptName} before progressing to ${demoConcepts.find((item) => item.id === conceptId)?.name}.`] : [`${demoConcepts.find((item) => item.id === conceptId)?.name ?? 'This concept'} is the next evidence-backed learning step.`]; if (latestOverride && overrideDecision) reasons.unshift(`Teacher override applied: ${latestOverride.reason}`); return { decision, conceptId, confidence: 82, mastery: state, reasons, blockingPrerequisites: blocking, recommendedAction: decision.toLowerCase() as DecisionResult['recommendedAction'], evaluatedAt: new Date().toISOString(), engineVersion: 'demo-v2.4', trace: { targetConcept: conceptId, prerequisiteChecks: blocking.map((item) => ({ concept: item.conceptName, mastery: item.mastery, threshold: item.threshold, passed: false })), rulesEvaluated: latestOverride && overrideDecision ? [{ rule: 'TEACHER_OVERRIDE', matched: true, details: { action: latestOverride.action } }] : [], finalDecision: decision } } }

export function demoTeacherData() {
  const alex = demoStates().reduce((sum, item) => sum + item.mastery_score, 0) / Math.max(1, demoStates().length)
  const students = [
    { id: DEMO_STUDENT_ID, initials: 'AC', name: 'Alex Carter', stage: 'Algebra Foundations', mastery: Math.round(alex), uncertainty: 22, recommendation: 'PRACTICE FRACTIONS', lastActive: 'Now', status: 'Needs attention' },
    { id: '00000000-0000-0000-0000-000000000002', initials: 'PS', name: 'Priya S.', stage: 'Linear Equations', mastery: 81, uncertainty: 10, recommendation: 'ADVANCE', lastActive: '1h ago', status: 'Improving' },
    { id: '00000000-0000-0000-0000-000000000003', initials: 'RK', name: 'Rahul K.', stage: 'Algebra Foundations', mastery: 45, uncertainty: 31, recommendation: 'REVIEW', lastActive: '3h ago', status: 'At risk' },
    { id: '00000000-0000-0000-0000-000000000004', initials: 'ZN', name: 'Zara N.', stage: 'Quadratics', mastery: 78, uncertainty: 12, recommendation: 'CHALLENGE', lastActive: 'Yesterday', status: 'Improving' },
  ]
  return { stats: { students: students.length, atRisk: students.filter((student) => student.status === 'At risk').length, needsReview: students.filter((student) => student.status === 'Needs attention').length, improving: students.filter((student) => student.status === 'Improving').length }, students }
}

export function demoTeacherWorkspace() {
  const states = demoStates()
  const attemptsSnapshot = demoAttempts()
  const teacher = demoTeacherData()
  const concepts = demoConcepts.map((concept) => {
    const state = states.find((item) => item.concept_id === concept.id)
    const conceptAttempts = attemptsSnapshot.filter((attempt) => attempt.conceptId === concept.id)
    const decision = demoDecision(concept.id)
    return { ...concept, mastery: Math.round(state?.mastery_score ?? 0), confidence: Math.round(state?.confidence_score ?? 0), attempts: conceptAttempts.length, correct: conceptAttempts.filter((attempt) => attempt.isCorrect).length, decision: decision.decision, blockers: decision.blockingPrerequisites, questionCount: demoQuestions.filter((question) => question.concept_id === concept.id).length }
  })
  const recentEvidence = attemptsSnapshot.slice(0, 10).map((attempt) => ({ ...attempt, conceptName: demoConcepts.find((concept) => concept.id === attempt.conceptId)?.name ?? 'Unknown concept' }))
  return { mode: 'demo' as const, stats: teacher.stats, students: teacher.students, concepts, prerequisites: demoPrerequisites, overrides: demoOverrides(), evidence: recentEvidence }
}
