import type { DecisionResult } from '@/lib/decision-engine'

export const DEMO_STUDENT_ID = '00000000-0000-0000-0000-000000000001'
const ids = { arithmetic: '10000000-0000-4000-8000-000000000001', fractions: '10000000-0000-4000-8000-000000000002', operations: '10000000-0000-4000-8000-000000000003', linear: '10000000-0000-4000-8000-000000000004', quadratic: '10000000-0000-4000-8000-000000000005', scientificMethod: '10000000-0000-4000-8000-000000000006', matterEnergy: '10000000-0000-4000-8000-000000000007' }
export function canonicalDemoConceptId(id: string) { const match = id.match(/([1-5])$/); return match ? Object.values(ids)[Number(match[1]) - 1] : id }
export const demoConcepts = [
  { id: ids.arithmetic, name: 'Basic Arithmetic', slug: 'basic-arithmetic', description: 'Core operations and number sense.', subject: 'ALGEBRA', difficulty: 'BEGINNER', estimated_minutes: 15, is_active: true },
  { id: ids.fractions, name: 'Fractions', slug: 'fractions', description: 'Equivalent fractions and operations.', subject: 'ALGEBRA', difficulty: 'BEGINNER', estimated_minutes: 20, is_active: true },
  { id: ids.operations, name: 'Algebraic Operations', slug: 'algebraic-operations', description: 'Simplify and manipulate expressions.', subject: 'ALGEBRA', difficulty: 'INTERMEDIATE', estimated_minutes: 25, is_active: true },
  { id: ids.linear, name: 'Linear Equations', slug: 'linear-equations', description: 'Solve equations one step at a time.', subject: 'ALGEBRA', difficulty: 'INTERMEDIATE', estimated_minutes: 25, is_active: true },
  { id: ids.quadratic, name: 'Quadratic Equations', slug: 'quadratic-equations', description: 'Build toward quadratic reasoning.', subject: 'ALGEBRA', difficulty: 'ADVANCED', estimated_minutes: 30, is_active: true },
  { id: ids.scientificMethod, name: 'Scientific Method', slug: 'scientific-method', description: 'Ask questions, test ideas, and interpret evidence.', subject: 'SCIENCE', difficulty: 'BEGINNER', estimated_minutes: 20, is_active: true },
  { id: ids.matterEnergy, name: 'Matter & Energy', slug: 'matter-energy', description: 'Explore states of matter and energy transfer.', subject: 'SCIENCE', difficulty: 'BEGINNER', estimated_minutes: 20, is_active: true },
]
export const demoPrerequisites = [ids.fractions, ids.operations, ids.linear, ids.quadratic].map((conceptId, index) => ({ id: `20000000-0000-4000-8000-00000000000${index + 1}`, concept_id: conceptId, prerequisite_concept_id: [ids.arithmetic, ids.fractions, ids.operations, ids.linear][index], required_mastery: 0.6, priority: 1 }))
type DemoQuestion = { id: string; concept_id: string; concept: typeof demoConcepts[number]; question: string; options: string[]; correctAnswer: string; explanation: string; difficulty: string; questionType: 'MCQ'; hintAvailable: boolean; hint: string }
export const demoQuestions: DemoQuestion[] = [
  { id: '30000000-0000-4000-8000-000000000001', concept_id: ids.operations, concept: demoConcepts[2], question: 'Simplify: 3x + 2x', options: ['5x', '6x', 'x⁵'], correctAnswer: '5x', explanation: 'Combine like terms by adding their coefficients.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Look for terms with the same variable.' },
  { id: '30000000-0000-4000-8000-000000000002', concept_id: ids.operations, concept: demoConcepts[2], question: 'Simplify: 2(a + 3)', options: ['2a + 3', '2a + 6', 'a + 6'], correctAnswer: '2a + 6', explanation: 'Distribute 2 to both terms inside the parentheses.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Multiply the outside number by each inside term.' },
  { id: '30000000-0000-4000-8000-000000000003', concept_id: ids.operations, concept: demoConcepts[2], question: 'What is the coefficient of y in 7y + 4?', options: ['4', '7', 'y'], correctAnswer: '7', explanation: 'The coefficient is the number multiplying the variable.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Find the number directly next to y.' },
  { id: '30000000-0000-4000-8000-000000000004', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 1/2 + 1/4?', options: ['2/6', '3/4', '1/6'], correctAnswer: '3/4', explanation: 'Convert both fractions to fourths, then add.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Use a common denominator of 4.' },
  { id: '30000000-0000-4000-8000-000000000005', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: x + 4 = 9', options: ['3', '5', '13'], correctAnswer: '5', explanation: 'Subtract 4 from both sides.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Undo the +4 operation.' },
  { id: '30000000-0000-4000-8000-000000000006', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 7 × 8?', options: ['48', '56', '64'], correctAnswer: '56', explanation: 'Seven groups of eight equal fifty-six.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think of 7 groups of 8.' },
  { id: '30000000-0000-4000-8000-000000000007', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 45 ÷ 5?', options: ['8', '9', '10'], correctAnswer: '9', explanation: 'Five groups of nine make forty-five.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think about the multiplication fact 5 × ? = 45.' },
  { id: '30000000-0000-4000-8000-000000000008', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 18 + 27?', options: ['35', '45', '55'], correctAnswer: '45', explanation: 'Add the tens and ones: 18 + 27 = 45.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Add 20, then add 7.' },
  { id: '30000000-0000-4000-8000-000000000009', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'Which number is prime?', options: ['21', '29', '35'], correctAnswer: '29', explanation: '29 has no factors other than 1 and itself.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Check whether any smaller prime divides it.' },
  { id: '30000000-0000-4000-8000-000000000010', concept_id: ids.arithmetic, concept: demoConcepts[0], question: 'What is 6²?', options: ['12', '30', '36'], correctAnswer: '36', explanation: '6² means 6 × 6, which equals 36.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Multiply 6 by itself.' },
]

demoQuestions.push(
  { id: '30000000-0000-4000-8000-000000000011', concept_id: ids.fractions, concept: demoConcepts[1], question: 'Which fraction is equivalent to 2/3?', options: ['4/6', '3/5', '5/8'], correctAnswer: '4/6', explanation: 'Multiply both numerator and denominator by 2.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Scale both parts by the same number.' },
  { id: '30000000-0000-4000-8000-000000000012', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 3/4 − 1/4?', options: ['1/2', '2/4', '3/8'], correctAnswer: '1/2', explanation: 'Subtract the numerators over the common denominator, then simplify.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'The denominators already match.' },
  { id: '30000000-0000-4000-8000-000000000013', concept_id: ids.fractions, concept: demoConcepts[1], question: 'What is 2/5 × 5?', options: ['2', '10/5', '1/5'], correctAnswer: '2', explanation: 'The 5 in the numerator and denominator cancel.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Rewrite 5 as 5/1.' },
  { id: '30000000-0000-4000-8000-000000000014', concept_id: ids.fractions, concept: demoConcepts[1], question: 'Which is larger?', options: ['3/8', '1/2', 'They are equal'], correctAnswer: '1/2', explanation: 'One half is four eighths, which is greater than three eighths.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Convert both to eighths.' },
  { id: '30000000-0000-4000-8000-000000000015', concept_id: ids.operations, concept: demoConcepts[2], question: 'Simplify: 4x − x', options: ['3x', '4', 'x³'], correctAnswer: '3x', explanation: 'Subtract the coefficients of like terms.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Treat x as 1x.' },
  { id: '30000000-0000-4000-8000-000000000016', concept_id: ids.operations, concept: demoConcepts[2], question: 'Evaluate 2x + 1 when x = 3.', options: ['5', '7', '9'], correctAnswer: '7', explanation: 'Substitute 3 for x: 2(3) + 1 = 7.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Replace x with 3.' },
  { id: '30000000-0000-4000-8000-000000000017', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: 2x = 14', options: ['6', '7', '12'], correctAnswer: '7', explanation: 'Divide both sides by 2.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Undo multiplication by 2.' },
  { id: '30000000-0000-4000-8000-000000000018', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: 3x − 2 = 10', options: ['2', '4', '6'], correctAnswer: '4', explanation: 'Add 2, then divide by 3.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Undo operations in reverse order.' },
  { id: '30000000-0000-4000-8000-000000000019', concept_id: ids.linear, concept: demoConcepts[3], question: 'Which value solves x/4 = 3?', options: ['7', '12', '16'], correctAnswer: '12', explanation: 'Multiply both sides by 4.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Undo division by 4.' },
  { id: '30000000-0000-4000-8000-000000000020', concept_id: ids.linear, concept: demoConcepts[3], question: 'Solve: 5 + x = 2x', options: ['3', '5', '10'], correctAnswer: '5', explanation: 'Subtract x from both sides, leaving 5 = x.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Collect x terms on one side.' },
  { id: '30000000-0000-4000-8000-000000000021', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'Which is a factorisation of x² + 5x + 6?', options: ['(x + 2)(x + 3)', '(x + 1)(x + 6)', '(x − 2)(x − 3)'], correctAnswer: '(x + 2)(x + 3)', explanation: 'Two numbers multiply to 6 and add to 5.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Look for factors of 6 that add to 5.' },
  { id: '30000000-0000-4000-8000-000000000022', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'What is the highest power in 3x² + x − 4?', options: ['1', '2', '4'], correctAnswer: '2', explanation: 'The degree is the highest exponent of the variable.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Find the largest exponent.' },
  { id: '30000000-0000-4000-8000-000000000023', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'Solve x² = 25.', options: ['x = 5 only', 'x = ±5', 'x = 25'], correctAnswer: 'x = ±5', explanation: 'Both 5² and (−5)² equal 25.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'A square has two possible roots.' },
  { id: '30000000-0000-4000-8000-000000000024', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'What is the discriminant of x² − 4x + 3?', options: ['4', '8', '16'], correctAnswer: '4', explanation: 'The discriminant is b² − 4ac = 16 − 12 = 4.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Use b² − 4ac.' },
  { id: '30000000-0000-4000-8000-000000000025', concept_id: ids.quadratic, concept: demoConcepts[4], question: 'Which graph represents a positive quadratic coefficient?', options: ['A parabola opening up', 'A parabola opening down', 'A straight line'], correctAnswer: 'A parabola opening up', explanation: 'A positive leading coefficient makes the parabola open upward.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think about the direction of the arms.' },
  { id: '30000000-0000-4000-8000-000000000026', concept_id: ids.scientificMethod, concept: demoConcepts[5], question: 'What is a testable explanation called?', options: ['A hypothesis', 'A conclusion', 'A measurement'], correctAnswer: 'A hypothesis', explanation: 'A hypothesis is a proposed explanation that can be tested.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'It is an idea you can investigate.' },
  { id: '30000000-0000-4000-8000-000000000027', concept_id: ids.scientificMethod, concept: demoConcepts[5], question: 'What should you do after collecting results?', options: ['Ignore them', 'Analyse the evidence', 'Change the question randomly'], correctAnswer: 'Analyse the evidence', explanation: 'Scientists analyse results to decide what the evidence shows.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Look for patterns in the data.' },
  { id: '30000000-0000-4000-8000-000000000028', concept_id: ids.scientificMethod, concept: demoConcepts[5], question: 'Which variable is deliberately changed in an investigation?', options: ['Independent variable', 'Control variable', 'Dependent variable'], correctAnswer: 'Independent variable', explanation: 'The independent variable is the factor the investigator changes.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'It is the input you choose to change.' },
  { id: '30000000-0000-4000-8000-000000000029', concept_id: ids.scientificMethod, concept: demoConcepts[5], question: 'Why repeat an experiment?', options: ['To make the result less reliable', 'To check consistency', 'To avoid recording data'], correctAnswer: 'To check consistency', explanation: 'Repeating an experiment helps identify unusual results and check reliability.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Reliable results can be reproduced.' },
  { id: '30000000-0000-4000-8000-000000000030', concept_id: ids.scientificMethod, concept: demoConcepts[5], question: 'Which is the best scientific conclusion?', options: ['It is definitely true forever', 'The evidence supports the hypothesis', 'The data does not matter'], correctAnswer: 'The evidence supports the hypothesis', explanation: 'Conclusions should match the evidence without claiming more than the data shows.', difficulty: 'HARD', questionType: 'MCQ', hintAvailable: true, hint: 'Use cautious language based on evidence.' },
  { id: '30000000-0000-4000-8000-000000000031', concept_id: ids.matterEnergy, concept: demoConcepts[6], question: 'Which state of matter has a fixed volume but no fixed shape?', options: ['Solid', 'Liquid', 'Gas'], correctAnswer: 'Liquid', explanation: 'A liquid keeps its volume but takes the shape of its container.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Think about water in different containers.' },
  { id: '30000000-0000-4000-8000-000000000032', concept_id: ids.matterEnergy, concept: demoConcepts[6], question: 'What happens when a solid is heated enough to melt?', options: ['It becomes a liquid', 'It becomes a gas immediately', 'It disappears'], correctAnswer: 'It becomes a liquid', explanation: 'Melting changes a solid into a liquid as particles gain energy.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'Ice melting is a familiar example.' },
  { id: '30000000-0000-4000-8000-000000000033', concept_id: ids.matterEnergy, concept: demoConcepts[6], question: 'Which form of energy is stored in food?', options: ['Chemical energy', 'Sound energy', 'Light energy'], correctAnswer: 'Chemical energy', explanation: 'Food stores energy in chemical bonds that can be released by the body.', difficulty: 'EASY', questionType: 'MCQ', hintAvailable: true, hint: 'It is released during digestion.' },
  { id: '30000000-0000-4000-8000-000000000034', concept_id: ids.matterEnergy, concept: demoConcepts[6], question: 'What is evaporation?', options: ['A liquid changing to a gas', 'A gas changing to a solid', 'A solid changing to a liquid'], correctAnswer: 'A liquid changing to a gas', explanation: 'Evaporation happens when particles at a liquid surface escape as a gas.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Think about a puddle drying.' },
  { id: '30000000-0000-4000-8000-000000000035', concept_id: ids.matterEnergy, concept: demoConcepts[6], question: 'Which material is a good conductor of electricity?', options: ['Copper', 'Rubber', 'Dry wood'], correctAnswer: 'Copper', explanation: 'Copper allows electric charge to move easily, so it is used in wires.', difficulty: 'MEDIUM', questionType: 'MCQ', hintAvailable: true, hint: 'Look for the metal used in electrical cables.' },
)
let attempts: Array<{ id: string; questionId: string; conceptId: string; question: string; isCorrect: boolean; submittedAt: string; usedHint: boolean }> = []
let mastery: Record<string, number> = { [ids.arithmetic]: 84, [ids.fractions]: 55, [ids.operations]: 28 }
export function isDemoMode() { return process.env.NODE_ENV !== 'production' && process.env.SEEKITO_DEMO_MODE === 'true' }
export function resetDemo() { attempts = []; mastery = { [ids.arithmetic]: 84, [ids.fractions]: 55, [ids.operations]: 28 } }
export function demoStates() { return Object.entries(mastery).map(([concept_id, mastery_score]) => ({ concept_id, mastery_score, confidence_score: Math.min(90, mastery_score + 10), attempt_count: attempts.filter((item) => item.conceptId === concept_id).length, correct_count: attempts.filter((item) => item.conceptId === concept_id && item.isCorrect).length, failure_count: attempts.filter((item) => item.conceptId === concept_id && !item.isCorrect).length, evidence_count: attempts.filter((item) => item.conceptId === concept_id).length, updated_at: new Date().toISOString() })) }
export function demoAttempts() { return attempts.slice().reverse() }
export function demoEvidence() { return attempts.slice().reverse().map((item) => ({ id: `e-${item.id}`, attempt_id: item.id, concept_id: item.conceptId, evidence_type: item.isCorrect ? 'CORRECT_INDEPENDENT' : 'INCORRECT', created_at: item.submittedAt })) }
export function demoSubmit(questionId: string, answer: string, usedHint: boolean) { const question = demoQuestions.find((item) => item.id === questionId); if (!question) return null; const isCorrect = answer.trim().toLowerCase() === question.correctAnswer.toLowerCase(); const id = `a-${Date.now()}`; attempts.push({ id, questionId, conceptId: question.concept_id, question: question.question, isCorrect, submittedAt: new Date().toISOString(), usedHint }); mastery[question.concept_id] = Math.max(0, Math.min(100, mastery[question.concept_id] + (isCorrect ? usedHint ? 10 : 20 : -15))); return { id, isCorrect, question } }
export function demoDecision(conceptId: string): DecisionResult { const state = mastery[conceptId] ?? 0; const blocking = demoPrerequisites.filter((edge) => edge.concept_id === conceptId && (mastery[edge.prerequisite_concept_id] ?? 0) < edge.required_mastery * 100).map((edge) => ({ conceptId: edge.prerequisite_concept_id, conceptName: demoConcepts.find((item) => item.id === edge.prerequisite_concept_id)?.name ?? 'Prerequisite', mastery: mastery[edge.prerequisite_concept_id] ?? 0, threshold: edge.required_mastery * 100 })); const decision = blocking.length ? 'BLOCKED' : state < 40 ? 'REMEDIATE' : state < 70 ? 'PRACTICE' : 'ADVANCE'; return { decision, conceptId, confidence: 82, mastery: state, reasons: blocking.length ? [`Strengthen ${blocking[0].conceptName} before progressing to ${demoConcepts.find((item) => item.id === conceptId)?.name}.`] : [`${demoConcepts.find((item) => item.id === conceptId)?.name ?? 'This concept'} is the next evidence-backed learning step.`], blockingPrerequisites: blocking, recommendedAction: decision.toLowerCase() as DecisionResult['recommendedAction'], evaluatedAt: new Date().toISOString(), engineVersion: 'demo-v2.4', trace: { targetConcept: conceptId, prerequisiteChecks: blocking.map((item) => ({ concept: item.conceptName, mastery: item.mastery, threshold: item.threshold, passed: false })), rulesEvaluated: [], finalDecision: decision } } }

export function demoTeacherData() {
  const alex = demoStates().reduce((sum, item) => sum + item.mastery_score, 0) / Math.max(1, demoStates().length)
  return { stats: { students: 32, atRisk: 4, needsReview: 7, improving: 18 }, students: [
    { id: DEMO_STUDENT_ID, initials: 'AC', name: 'Alex Carter', stage: 'Algebra Foundations', mastery: Math.round(alex), uncertainty: 22, recommendation: 'PRACTICE FRACTIONS', lastActive: 'Now', status: 'Needs attention' },
    { id: '00000000-0000-0000-0000-000000000002', initials: 'PS', name: 'Priya S.', stage: 'Linear Equations', mastery: 81, uncertainty: 10, recommendation: 'ADVANCE', lastActive: '1h ago', status: 'Improving' },
    { id: '00000000-0000-0000-0000-000000000003', initials: 'RK', name: 'Rahul K.', stage: 'Algebra Foundations', mastery: 45, uncertainty: 31, recommendation: 'REVIEW', lastActive: '3h ago', status: 'At risk' },
    { id: '00000000-0000-0000-0000-000000000004', initials: 'ZN', name: 'Zara N.', stage: 'Quadratics', mastery: 78, uncertainty: 12, recommendation: 'CHALLENGE', lastActive: 'Yesterday', status: 'Improving' },
  ] }
}
