'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { RoleShell } from '@/components/layout/RoleShell'

type Student = { id: string; initials: string; name: string; stage: string; mastery: number; uncertainty: number; recommendation: string; lastActive: string; status: string }
type TeacherData = { stats: { students: number; atRisk: number; needsReview: number; improving: number }; students: Student[]; evidence?: Array<{ id: string; conceptName: string; isCorrect: boolean; usedHint: boolean; hintCount?: number; responseTimeMs?: number | null; retryNumber?: number; submittedAt: string }> }

export default function TeacherPage() {
  const [data, setData] = useState<TeacherData | null>(null)
  const [learnerName, setLearnerName] = useState('Current learner')
  useEffect(() => { const sync = () => { let name = ''; try { name = JSON.parse(localStorage.getItem('seekito-profile') ?? '{}').name?.trim() ?? '' } catch {} setLearnerName(name || 'Current learner'); fetch('/api/teacher/workspace').then((r) => r.ok ? r.json() : Promise.reject(new Error('Unable to load teacher workspace'))).then((body) => { const workspace = body.workspace; if (name && workspace?.students?.[0]) workspace.students[0] = { ...workspace.students[0], name, initials: name.split(' ').map((part: string) => part[0]).join('').slice(0, 2).toUpperCase() }; setData(workspace) }).catch(() => setData(null)) }; sync(); window.addEventListener('seekito-profile-updated', sync); return () => window.removeEventListener('seekito-profile-updated', sync) }, [])
  return <RoleShell role="teacher" eyebrow="Teacher console" title="Class Overview" description="Evidence-backed learner signals, recommendations, and intervention context.">
    <div className="teacher-demo-page">
      <div className="teacher-demo-actions"><span className="teacher-live-status"><i /> {data ? 'Workspace data connected' : 'Loading workspace…'}</span><Link className="role-dark-button" href="/teacher/analytics">View analytics</Link></div>
      <section className="teacher-metric-grid">{[['STUDENTS', data?.stats.students ?? '—', '2 new vs last week'], ['AT RISK', data?.stats.atRisk ?? '—', '−1 vs last week'], ['NEEDS REVIEW', data?.stats.needsReview ?? '—', '+2 vs last week'], ['IMPROVING', data?.stats.improving ?? '—', '+5 vs last week']].map(([label, value, note]) => <article className="teacher-metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
      <section className="teacher-table-card"><div className="teacher-table-header"><div><p className="eyebrow">LEARNER SIGNALS</p><h2>Students who need your attention</h2></div><Link className="teacher-link" href="/teacher/students">View all students →</Link></div><div className="teacher-student-table"><div className="teacher-table-heading"><span>STUDENT</span><span>STAGE</span><span>MASTERY</span><span>RECOMMENDATION</span><span>LAST ACTIVE</span></div>{data?.students.slice(0, 4).map((student) => <Link className="teacher-table-row" href={`/teacher/students?student=${student.id}`} key={student.id}><span className="teacher-student-name"><b>{student.initials}</b><strong>{student.name}</strong></span><span>{student.stage}</span><strong>{student.mastery}%</strong><span><em className={`teacher-tag ${student.recommendation.includes('PRACTICE') || student.recommendation === 'REVIEW' ? 'warn' : 'good'}`}>{student.recommendation}</em></span><span>{student.lastActive}</span></Link>) ?? <div className="teacher-loading">Loading learner signals…</div>}</div></section>
      <section className="teacher-table-card"><div className="teacher-table-header"><div><p className="eyebrow">EVIDENCE SIGNALS · {learnerName.toUpperCase()}</p><h2>Recent learner attempts</h2></div><Link className="teacher-link" href="/teacher/insights">View decision trace →</Link></div><div className="teacher-student-table teacher-evidence-list"><div className="teacher-table-heading"><span>LEARNER</span><span>CONCEPT</span><span>RESULT</span><span>HINTS</span><span>RETRIES</span><span>RESPONSE TIME</span></div>{data?.evidence?.slice(0, 6).map((item) => <div className="teacher-table-row" key={item.id}><span><strong>{learnerName}</strong><small>{new Date(item.submittedAt).toLocaleTimeString()}</small></span><span>{item.conceptName}</span><strong className={item.isCorrect ? 'result-correct' : 'result-incorrect'}>{item.isCorrect ? 'Correct' : 'Incorrect'}</strong><span>{item.usedHint ? `×${item.hintCount ?? 1}` : '0'}</span><span>{item.retryNumber ? `×${item.retryNumber}` : '0'}</span><span>{item.responseTimeMs != null ? `${Math.round(item.responseTimeMs / 100) / 10}s` : '—'}</span></div>) ?? <div className="teacher-loading">No attempts captured yet.</div>}{data && !data.evidence?.length && <div className="teacher-loading">No attempts captured yet. Submit a diagnostic or practice answer to populate these signals.</div>}</div></section>
      <section className="teacher-insight-callout"><div><p className="eyebrow">DECISION ENGINE V2.4</p><h2>Every recommendation comes with a reason.</h2><p>Review evidence, learner state, and prerequisite checks before you intervene.</p></div><Link className="role-light-button" href="/teacher/insights">Explore decision history</Link></section>
    </div>
  </RoleShell>
}
