'use client'

import { useEffect, useState } from 'react'
import { RoleShell } from '@/components/layout/RoleShell'

type Student = { initials: string; name: string; stage: string; mastery: number; uncertainty: number; recommendation: string; lastActive: string }
export default function LearnerStatesPage() {
  const [students, setStudents] = useState<Student[]>([])
  useEffect(() => { fetch('/api/demo/teacher').then((response) => response.json()).then((data) => setStudents(data.students ?? [])) }, [])
  return <><style jsx global>{`.learner-state-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.learner-state-card{padding:22px;border:1px solid var(--line);border-radius:14px;background:var(--surface);box-shadow:0 8px 22px rgba(40,35,80,.035)}.learner-state-card header{display:flex;align-items:center;justify-content:space-between;gap:12px}.learner-state-card>p{margin:14px 0 20px;color:var(--muted);font-size:12px}.learner-state-stat{display:flex;align-items:end;justify-content:space-between}.learner-state-stat span,.learner-state-meta,.learner-state-evidence{color:var(--muted);font-size:12px}.learner-state-stat strong{color:var(--ink);font-size:28px}.state-bar{height:9px;margin:10px 0 16px;border-radius:999px;background:#ebe9e5;overflow:hidden}.state-bar i{display:block;height:100%;border-radius:inherit;background:var(--primary)}.learner-state-meta{display:flex;justify-content:space-between;gap:12px;padding-bottom:16px;border-bottom:1px solid var(--line)}.learner-state-meta strong{color:var(--ink)}.learner-state-evidence{display:flex;justify-content:space-between;gap:12px;padding-top:15px}.learner-state-evidence strong{color:var(--ink);font-size:11px;text-align:right}@media(max-width:700px){.learner-state-grid{grid-template-columns:1fr}.learner-state-card{padding:18px}}`}</style><RoleShell role="teacher" eyebrow="Teacher console" title="Learner States" description="The living model Seekito maintains for each learner—updated as evidence is captured.">
    <div className="teacher-demo-page"><div className="teacher-demo-actions"><span className="teacher-live-status"><i /> State model synced · 4 active profiles</span><span className="eyebrow">LAST UPDATED JUST NOW</span></div>
      <section className="learner-state-grid">{students.map((student) => <article className="learner-state-card" key={student.name}><header><span className="teacher-student-name"><b>{student.initials}</b><strong>{student.name}</strong></span><em className={`teacher-tag ${student.mastery < 60 ? 'warn' : 'good'}`}>{student.recommendation}</em></header><p>{student.stage}</p><div className="learner-state-stat"><span>Mastery</span><strong>{student.mastery}%</strong></div><div className="state-bar"><i style={{ width: `${student.mastery}%` }} /></div><div className="learner-state-meta"><span>Uncertainty <strong>{student.uncertainty}%</strong></span><span>Last active <strong>{student.lastActive}</strong></span></div><div className="learner-state-evidence"><span>Evidence captured</span><strong>{student.name === 'Alex Carter' ? '6 attempts · 2 hints' : 'Recent signals available'}</strong></div></article>)}</section>
      <section className="teacher-insight-callout"><div><p className="eyebrow">HOW TO READ THIS</p><h2>Mastery tells you where. Uncertainty tells you how sure.</h2><p>Use both signals with recent evidence before planning an intervention.</p></div></section>
    </div>
  </RoleShell></>
}
