'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { RoleShell } from '@/components/layout/RoleShell'
type Workspace = { students?: Array<{ name: string }>; evidence: Array<{ id: string; conceptName: string; isCorrect: boolean; usedHint: boolean; hintCount?: number; responseTimeMs?: number | null; retryNumber?: number; submittedAt: string }>; concepts: Array<{ id: string; name: string; mastery: number; decision: string; blockers: Array<{ conceptName: string; mastery: number; threshold: number }> }> }
export default function TeacherInsightsPage() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null)
  const [studentName, setStudentName] = useState('Learner')
  useEffect(() => { const sync = () => { let name = ''; try { name = JSON.parse(localStorage.getItem('seekito-profile') ?? '{}').name?.trim() ?? '' } catch {} fetch('/api/teacher/workspace').then((response) => response.json()).then((body) => { const next = body.workspace ?? null; if (name && next?.students?.[0]) next.students[0] = { ...next.students[0], name }; setWorkspace(next); setStudentName(name || next?.students?.[0]?.name || 'Learner') }) }; sync(); window.addEventListener('seekito-profile-updated', sync); return () => window.removeEventListener('seekito-profile-updated', sync) }, [])
  const focus = workspace?.concepts.find((concept) => concept.name === 'Fractions') ?? workspace?.concepts[0]
  const evidence = workspace?.evidence ?? []
  const decision = focus?.decision ?? 'PRACTICE'
  return <RoleShell role="teacher" eyebrow="Decision history" title="Why this recommendation?" description="A transparent trace from learner evidence to the next best action."><div className="teacher-demo-page teacher-insight-layout"><section className="teacher-proof-card teacher-trace-card"><p className="eyebrow">{studentName.toUpperCase()} · LIVE DECISION TRACE</p><h2>Seekito recommends {decision.toLowerCase()}.</h2><p>Every recommendation is computed from captured evidence, learner state, and prerequisite checks.</p>{[['Evidence', `${evidence.length} attempts analysed`],['Learner State', `${focus?.name ?? 'Current concept'} mastery ${focus?.mastery ?? 0}%`],['Prerequisite Check', focus?.blockers?.length ? `${focus.blockers[0].conceptName} is below the ${focus.blockers[0].threshold}% gate` : 'All prerequisites are ready'],['Decision', decision],['Recommendation', `${focus?.name ?? 'Next concept'} learning path`]].map(([title, detail], index) => <div className="teacher-trace-row" key={title}><b>{index + 1}</b><span><strong>{title}</strong><small>{detail}</small></span></div>)}<Link className="role-dark-button" href={`/student/learn/${focus?.id ?? '10000000-0000-4000-8000-000000000002'}`}>Open student learning path</Link></section><section className="teacher-proof-card"><p className="eyebrow">RECENT LEARNER ATTEMPTS</p><h2>Evidence history</h2>{evidence.length ? <div className="teacher-evidence-list">{evidence.slice(0, 6).map((item) => <div className="teacher-history-row" key={item.id}><small>{new Date(item.submittedAt).toLocaleTimeString()}</small><strong>{item.isCorrect ? 'CORRECT' : 'INCORRECT'}</strong><span>{item.conceptName}</span><small>{item.usedHint ? `Hint ×${item.hintCount ?? 1}` : 'Independent'}</small><small>{item.responseTimeMs != null ? `${Math.round(item.responseTimeMs / 100) / 10}s` : '—'}</small><small>{item.retryNumber ? `Retry ${item.retryNumber}` : 'First attempt'}</small></div>)}</div> : <p className="muted">No attempts captured for {studentName} yet. Submit a diagnostic or practice answer, then refresh this page.</p>}</section></div></RoleShell>
}
